--- Simplified network model, to be used by wrappers
mod NETWORK is
pr CONFIGURATION .
pr STRING .

--- Can subsort MessageContent to pass custom messages on the network
sort MessageContent .
subsort String < MessageContent .

--- Open a connection from object A to object B
op open_to_ : Oid Oid -> Msg [ctor msg] .

--- Send message on a connection from object A to object B
op msg_from_to_ : MessageContent Oid Oid -> Msg [ctor msg] .

--- Close connection between object A to object B
op close_to_ : Oid Oid -> Msg [ctor msg] .

vars A B : Oid .

--- For now, close just removes open
rl [close] :
  (open A to B)
  (close A to B)
=>
  none
  .
endm