--- Simplified network model, to be used by wrappers
mod NETWORK is
pr CONFIGURATION .
pr STRING .
pr INT .

--- Can subsort MessageContent to pass custom messages on the network
sort MessageContent .
subsort String < MessageContent .

--- Send message on a connection from object A to object B
op msg_from_to_ : MessageContent Oid Oid -> Msg [ctor msg] .
op noMsg : -> Msg [ctor] .

sort Buffer .
subsort Msg < Buffer .
op mtB : -> Buffer [ctor] .
op _,_ : Buffer Buffer -> Buffer [ctor assoc id: mtB] .

op msgBuffer:_ : Buffer -> Attribute [ctor] .
op bufferLen:_ : Int -> Attribute [ctor] .
op maxBufferLen:_ : Int -> Attribute [ctor] .

vars Buff : Buffer .
vars M M' : Msg .
vars N : Nat .
--- Replace at index
op replace : Buffer Msg Nat -> Buffer .
ceq replace((M', Buff), M, N) = (M', replace(Buff, M, (N - 1))) if N >= 1 .
ceq replace((M', Buff), M, N) = (M, Buff) if N == 0 .
ceq replace(Buff, M, N) = mtB if Buff == mtB .

op Client : -> Cid [ctor] .
op Server : -> Cid [ctor] .

op untilDelim : String String -> String .
op afterDelim : String String -> String .

vars S Delim Data Rest : String .

ceq untilDelim(S, Delim) = Data if 
  N    := find(S, Delim, 0) /\
  Data := substr(S, 0, N) .

ceq afterDelim(S, Delim) = Data if 
  N    := find(S, Delim, 0) /\
  Data := substr(S, N + 1, length(S)) .
endm