--- Represents a collection of configurations
--- Used so that we can have "global" state
--- A rewrite rule can be rewritten to:
***(
rl : C => C' .

rl : { C Config } => { C' Config } .
)
--- This allows you to inspect the 'rest' of the configuration
--- A rule matching just C Config (not {C Config}) would be able to match many different configs to the "Config" variable
mod STATE is
pr CONFIGURATION .
pr NAT .

sort State .
op {_} : Configuration -> State [ctor] .

--- The world is a State stored in an attribute
op world:_ : State -> Attribute [ctor] .
op world : Nat State -> Attribute [ctor] .
endm