load socks.maude

mod CLIENT is
pr CONFIGURATION .
pr SOCKS .

vars N N' N'' N''' Port : Nat .
vars Address S S' Rest : String .
vars Config : Configuration .
vars Me CM SocketName : Oid .
vars Att : AttributeSet .

op createClient : Nat String -> Msg [ctor msg] .

op client : Nat -> Oid [ctor] .
op Client : -> Cid [ctor] .

op clientManager : -> Oid [ctor] .
op ClientManager : -> Cid [ctor] .

op nextNumber:_ : Nat -> Attribute [ctor] .

sort ClientState .
ops initial connecting sendingHeader readingMethod sendingRequest readingRequestReply sendingWebsiteMsg readingWebsiteMsg : -> ClientState [ctor] .

op state:_ : ClientState -> Attribute [ctor] .
op address:_ : Nat -> Attribute [ctor] .
op port:_ : Nat -> Attribute [ctor] .
op socketName:_ : Oid -> Attribute [ctor] .
op read:_ : String -> Attribute [ctor] .

op clientManagerInConfig : Configuration -> Bool .
eq clientManagerInConfig(< CM : ClientManager | Att > Config) = true .
eq clientManagerInConfig(Config) = false [owise] .


--- From SOCKS maude
op findNth : String String Nat Nat -> FindResult .
eq findNth(S, S', N, 0) = find(S, S', N) .
ceq findNth(S, S', N, N') = findNth(S, S', find(S, S', N) + 1, N' - 1) if N' =/= 0 .

op addressToBytes : String Nat -> String .
--- String address has type 3
eq addressToBytes(S, 3) = char(length(S)) + S .
--- IPV4 address has type 1
ceq addressToBytes(S, 1) = 
  char(N) + char(N') + char(N'') + char(N''')
if
  N := rat(substr(S, 0, findNth(S, ".", 0, 0)), 10) /\
  N' := rat(substr(S, findNth(S, ".", 0, 0) + 1, find(substr(S, findNth(S, ".", 0, 0) + 1, length(S)), ".", 0)), 10) /\
  N'' := rat(substr(S, findNth(S, ".", 0, 1) + 1, find(substr(S, findNth(S, ".", 0, 1) + 1, length(S)), ".", 0)), 10) /\
  N''' := rat(substr(S, findNth(S, ".", 0, 2) + 1, length(S)), 10)
  .

op portToBytes : Nat -> String .
eq portToBytes(N) = char(N quo (2 ^ 8)) + char(N rem (2 ^ 8)) .
--- end From SOCKS

crl [createClientManager] :
  { Config }
=>
  {
    < clientManager : ClientManager | nextNumber: 0 >
    Config
  }

if
  not clientManagerInConfig(Config)
  .

rl [createClient] :
  createClient(Port, Address)
  < CM : ClientManager | nextNumber: N, Att >
=>
  < client(N) : Client | state: initial, address: Address, port: Port, read: "" >
  < CM : ClientManager | nextNumber: s(N), Att >
  .

rl [receive] :
  < Me : Client | socketName: SocketName, read: S, Att >
  received(Me, SocketName, S')
=>
  < Me : Client | socketName: SocketName, read: (S + S'), Att >
  receive(SocketName, Me)
  .

rl [sent] :
  < Me : Client | socketName: SocketName, Att >
  sent(Me, SocketName)
=>
  < Me : Client | socketName: SocketName, Att >
  .

rl [connectToServer] :
  < Me : Client | state: initial, address: Address, port: Port, Att >
=>
  createClientTcpSocket(socketManager, Me, "127.0.0.1", 1234)
  < Me : Client | state: connecting, address: Address, port: Port, Att >
  .

rl [connectedToServer] :
  < Me : Client | state: connecting, Att >
  createdSocket(Me, socketManager, SocketName)
=>
  < Me : Client | state: sendingHeader, socketName: SocketName, Att >
  receive(SocketName, Me)
  .

rl [sendHeader] :
  < Me : Client | state: sendingHeader, socketName: SocketName, Att >
=>
  send(SocketName, Me, char(5) + char(1) + char(0))
  < Me : Client | state: readingMethod, socketName: SocketName, Att >
  .

crl [readMethod] :
  < Me : Client | state: readingMethod, socketName: SocketName, read: S, Att >
=>
  < Me : Client | state: sendingRequest, socketName: SocketName, read: Rest, Att >
if
  length(S) >= 2 /\
  Rest := substr(S, 2, length(S))
  .

rl [sendRequest] :
  < Me : Client | state: sendingRequest, socketName: SocketName, address: Address, port: Port, Att >
=>
  send(SocketName, Me, char(5) + char(1) + char(0) + char(1) + addressToBytes(Address, 1) + portToBytes(Port))
  < Me : Client | state: readingRequestReply, socketName: SocketName, address: Address, port: Port, Att >
  .

crl [readRequestReply] :
  < Me : Client | state: readingRequestReply, socketName: SocketName, read: S, Att >
=>
  < Me : Client | state: sendingWebsiteMsg, socketName: SocketName, read: Rest, Att >
if
  length(S) >= 10 /\
  Rest := substr(S, 10, length(S))
  .

rl [sendWebsiteMsg] : 
  < Me : Client | state: sendingWebsiteMsg, socketName: SocketName, Att >
=>
  send(SocketName, Me, "hello")
  < Me : Client | state: readingWebsiteMsg, socketName: SocketName, Att >
  .


endm

mod TEST is
pr CONFIGURATION .
pr SOCKS .
pr CLIENT .

op start : -> Configuration [ctor] .

rl [start] :
  { start }
=>
  {
    <>
    createSocksServer(1234, "100.101.102.103")
    createClient(1235, "100.101.102.103")
    createClient(1236, "100.101.102.103")
  }
  .

endm