load socks.maude
load ibos-socket.maude

mod CLIENT is
pr CONFIGURATION .
pr SOCKS .

vars N N' N'' N''' Port : Nat .
vars Address S S' Rest : String .
vars Config : Configuration .
vars Me CM SocketName : Oid .
vars Att : AttributeSet .

op createClient : Nat String -> Msg [ctor msg] .

op client : Nat -> Oid [ctor] .
op Client : -> Cid [ctor] .

op clientManager : -> Oid [ctor] .
op ClientManager : -> Cid [ctor] .

op nextNumber:_ : Nat -> Attribute [ctor] .

sort ClientState .
ops initial connecting sendingHeader readingMethod sendingRequest readingRequestReply sendingWebsiteMsg readingWebsiteMsg : -> ClientState [ctor] .

op state:_ : ClientState -> Attribute [ctor] .
op address:_ : Nat -> Attribute [ctor] .
op port:_ : Nat -> Attribute [ctor] .
op socketName:_ : Oid -> Attribute [ctor] .
op read:_ : String -> Attribute [ctor] .

op clientManagerInConfig : Configuration -> Bool .
eq clientManagerInConfig(< CM : ClientManager | Att > Config) = true .
eq clientManagerInConfig(Config) = false [owise] .


--- From SOCKS maude
op findNth : String String Nat Nat -> FindResult .
eq findNth(S, S', N, 0) = find(S, S', N) .
ceq findNth(S, S', N, N') = findNth(S, S', find(S, S', N) + 1, N' - 1) if N' =/= 0 .

op addressToBytes : String Nat -> String .
--- String address has type 3
eq addressToBytes(S, 3) = char(length(S)) + S .
--- IPV4 address has type 1
ceq addressToBytes(S, 1) = 
  char(N) + char(N') + char(N'') + char(N''')
if
  N := rat(substr(S, 0, findNth(S, ".", 0, 0)), 10) /\
  N' := rat(substr(S, findNth(S, ".", 0, 0) + 1, find(substr(S, findNth(S, ".", 0, 0) + 1, length(S)), ".", 0)), 10) /\
  N'' := rat(substr(S, findNth(S, ".", 0, 1) + 1, find(substr(S, findNth(S, ".", 0, 1) + 1, length(S)), ".", 0)), 10) /\
  N''' := rat(substr(S, findNth(S, ".", 0, 2) + 1, length(S)), 10)
  .

op portToBytes : Nat -> String .
eq portToBytes(N) = char(N quo (2 ^ 8)) + char(N rem (2 ^ 8)) .
--- end From SOCKS

crl [createClientManager] :
  { Config }
=>
  {
    < clientManager : ClientManager | nextNumber: 0 >
    Config
  }
if
  not clientManagerInConfig(Config)
  .

rl [createClient] :
  createClient(Port, Address)
  < CM : ClientManager | nextNumber: N, Att >
=>
  < client(N) : Client | state: initial, address: Address, port: Port, read: "" >
  < CM : ClientManager | nextNumber: s(N), Att >
  .

rl [receive] :
  < Me : Client | socketName: SocketName, read: S, Att >
  received(Me, SocketName, S')
=>
  < Me : Client | socketName: SocketName, read: (S + S'), Att >
  receive(SocketName, Me)
  .

rl [sent] :
  < Me : Client | socketName: SocketName, Att >
  sent(Me, SocketName)
=>
  < Me : Client | socketName: SocketName, Att >
  .

rl [connectToServer] :
  < Me : Client | state: initial, address: Address, port: Port, Att >
=>
  createClientTcpSocket(socketManager, Me, "127.0.0.1", 8081)
  < Me : Client | state: connecting, address: Address, port: Port, Att >
  .

rl [connectedToServer] :
  < Me : Client | state: connecting, Att >
  createdSocket(Me, socketManager, SocketName)
=>
  < Me : Client | state: sendingRequest, socketName: SocketName, Att >
  receive(SocketName, Me)
  .
***(
rl [sendHeader] :
  < Me : Client | state: sendingHeader, socketName: SocketName, Att >
=>
  send(SocketName, Me, char(5) + char(1) + char(0))
  < Me : Client | state: readingMethod, socketName: SocketName, Att >
  .

crl [readMethod] :
  < Me : Client | state: readingMethod, socketName: SocketName, read: S, Att >
=>
  < Me : Client | state: sendingRequest, socketName: SocketName, read: Rest, Att >
if
  length(S) >= 2 /\
  Rest := substr(S, 2, length(S))
  .
)

rl [sendRequest] :
  < Me : Client | state: sendingRequest, socketName: SocketName, address: Address, port: Port, Att >
=>
  send(SocketName, Me, char(5) + char(1) + char(0) + char(1) + addressToBytes(Address, 1) + portToBytes(Port))
  < Me : Client | state: readingRequestReply, socketName: SocketName, address: Address, port: Port, Att >
  .

crl [readRequestReply] :
  < Me : Client | state: readingRequestReply, socketName: SocketName, read: S, Att >
=>
  < Me : Client | state: sendingWebsiteMsg, socketName: SocketName, read: Rest, Att >
if
  length(S) >= 10 /\
  Rest := substr(S, 10, length(S))
  .

rl [sendWebsiteMsg] : 
  < Me : Client | state: sendingWebsiteMsg, socketName: SocketName, Att >
=>
  send(SocketName, Me, "hello")
  < Me : Client | state: readingWebsiteMsg, socketName: SocketName, Att >
  .

endm

mod UI is
pr CONFIGURATION .
pr CLIENT .
pr IBOS-EXTEND .

op UI : -> Cid .
op ui : -> Oid .

op serverSocket:_ : Oid -> Attribute [ctor] .
op ibosSocket:_ : Oid -> Attribute [ctor] .

op didIt:_ : Bool -> Attribute [ctor] .

vars Att : AttributeSet .
vars Sock NewSock : Oid .

op createUI : -> Msg [ctor] .

rl [createUI] : 
  createUI 
=> 
  < ui : UI | didIt: false >
  createServerTcpSocket(socketManager, ui, 8080, 5)
  .

rl [createdUISocket] :
  createdSocket(ui, socketManager, Sock)
  < ui : UI | Att >
=>
  < ui : UI | serverSocket: Sock, Att >
  acceptClient(Sock, ui)
  .

rl [acceptedClient] :
  acceptedClient(ui, Sock, "127.0.0.1", NewSock)
  < ui : UI | Att >
=>
  < ui : UI | ibosSocket: NewSock, Att >
  send(NewSock, ui, "MSG-NEW-URL|url0|100.101.102.103#")
  .

--- DEAR LORD FORGIVE ME
--- how can we check IBOS is done processing before creating the client other than this?

rl [ibosReady] :
  < kernel | msgPolicy(policy(webapp,
    network, MSG-FETCH-URL),ps policy(network, webapp, MSG-RETURN-URL),ps policy(ui,
    webapp, MSG-NEW-URL),ps policy(ui, webapp, MSG-SWITCH-TAB)),nextNPN(2),
    handledCurrently(none),weblabels(pi(webapp(0), url("0")),wp pi(webapp(1), url("url0",
    "100.101.102.103"))),netlabels(pi(network(0), url("0"), url("0")),np pi(network(1),
    url("url0", "100.101.102.103"), url("url0", "100.101.102.103"))),displayedTopBar(url(
    "url0", "100.101.102.103")) > < display | activeWebapp(webapp(1)),displayedContent(url(
    "url0", "100.101.102.103")) > < nic | in(mtLL),nic-out(mtLS) > < webappmgr | nextWPN(2)
    > < ui | toKernel(mt) > < webapp(0) | rendered(url("0")),URL(url("0")),loading(true),
    fromKernel(mt),toKernel(mt) > < webapp(1) | rendered(url("url0", "100.101.102.103")),
    URL(url("url0", "100.101.102.103")),loading(true),fromKernel(mt),toKernel(mt) > <
    network(0) | fromKernel(mt),toKernel(mt),returnTo(webapp(0)),in(mtLL),out(mtLL),mem-in(
    nolabel),mem-out(nolabel) > < network(1) | fromKernel(mt),toKernel(mt),returnTo(webapp(
    1)),in(mtLL),out(mtLL),mem-in(nolabel),mem-out(nolabel) > < socketManager :
    SocketManager | nextNumber: 4,connections: (connectionFromTo(1, 2, ""),
    connectionFromTo(2, 1, "")),localServers: (localServer(0, 8080),localServer(3, 8081)) >
    < clientManager : ClientManager | nextNumber: 0 > < socketClient : SocketClient | read:
    "",state: active,name: socket(1) > < stateTracker : StateTracker | lastNetlabels: pi(
    network(1), url("url0", "100.101.102.103"), url("url0", "100.101.102.103")),
    procAndPort: npap(pi(network(1), url("url0", "100.101.102.103"), url("url0",
    "100.101.102.103")), 8081),nextPort: 8082 > <
    socksServer(8081) : SocksServer | whitelistedAddress: "100.101.102.103",socketName:
    socket(3),nextClientID: 0 >

    < ui : UI | didIt: false, Att >
  =>
  < kernel | msgPolicy(policy(webapp,
    network, MSG-FETCH-URL),ps policy(network, webapp, MSG-RETURN-URL),ps policy(ui,
    webapp, MSG-NEW-URL),ps policy(ui, webapp, MSG-SWITCH-TAB)),nextNPN(2),
    handledCurrently(none),weblabels(pi(webapp(0), url("0")),wp pi(webapp(1), url("url0",
    "100.101.102.103"))),netlabels(pi(network(0), url("0"), url("0")),np pi(network(1),
    url("url0", "100.101.102.103"), url("url0", "100.101.102.103"))),displayedTopBar(url(
    "url0", "100.101.102.103")) > < display | activeWebapp(webapp(1)),displayedContent(url(
    "url0", "100.101.102.103")) > < nic | in(mtLL),nic-out(mtLS) > < webappmgr | nextWPN(2)
    > < ui | toKernel(mt) > < webapp(0) | rendered(url("0")),URL(url("0")),loading(true),
    fromKernel(mt),toKernel(mt) > < webapp(1) | rendered(url("url0", "100.101.102.103")),
    URL(url("url0", "100.101.102.103")),loading(true),fromKernel(mt),toKernel(mt) > <
    network(0) | fromKernel(mt),toKernel(mt),returnTo(webapp(0)),in(mtLL),out(mtLL),mem-in(
    nolabel),mem-out(nolabel) > < network(1) | fromKernel(mt),toKernel(mt),returnTo(webapp(
    1)),in(mtLL),out(mtLL),mem-in(nolabel),mem-out(nolabel) > < socketManager :
    SocketManager | nextNumber: 4,connections: (connectionFromTo(1, 2, ""),
    connectionFromTo(2, 1, "")),localServers: (localServer(0, 8080),localServer(3, 8081)) >
    < clientManager : ClientManager | nextNumber: 0 > < socketClient : SocketClient | read:
    "",state: active,name: socket(1) > < stateTracker : StateTracker | lastNetlabels: pi(
    network(1), url("url0", "100.101.102.103"), url("url0", "100.101.102.103")),
    procAndPort: npap(pi(network(1), url("url0", "100.101.102.103"), url("url0",
    "100.101.102.103")), 8081),nextPort: 8082 > < ui : UI | ibosSocket: socket(2) > <
    socksServer(8081) : SocksServer | whitelistedAddress: "100.101.102.103",socketName:
    socket(3),nextClientID: 0 >

    createClient(1234, "100.101.102.103")
    < ui : UI | didIt: true, Att >
    .

endm

mod TEST is
pr CONFIGURATION .
pr SOCKS .
pr CLIENT .
pr UI .
pr IBOS-EXTEND .

vars S S' Delim Data Address Rest : String .
vars N Port : Nat .
vars Me : Oid .
vars Att : AttributeSet .

--- Invariants for testing
op untilDelim : String String -> String .
op afterDelim : String String -> String .

ceq untilDelim(S, Delim) = Data if 
  N    := find(S, Delim, 0) /\
  Data := substr(S, 0, N) .

ceq afterDelim(S, Delim) = Data if 
  N    := find(S, Delim, 0) /\
  Data := substr(S, N + 1, length(S)) .

op isBufferFullOf : String String -> Bool .

eq isBufferFullOf("", S) = true .
ceq isBufferFullOf(S, S') =
  Data == S' and isBufferFullOf(Rest, S')
if
  Data := untilDelim(S, "#") /\
  Rest := afterDelim(S, "#") /\
  length(S) > 0
  . 

var Config : Configuration .

op I : State -> Bool .

eq I(
  {
    < Me : Client | state: readingWebsiteMsg, address: Address, port: Port, read: S, Att >
    Config
  }) = isBufferFullOf(S,  Address + ":" + string(Port, 10)) and I({Config}) .

eq I({Config}) = true [owise] .
--- End invariants

op startTest : -> Configuration [ctor] .

rl [startTest] :
  { startTest }
=>
  {
    <>
    startIBOS
    createUI
    ---createSocksServer(1234, "100.101.102.103")
    ---createClient(1235, "100.101.102.103")

  }
  .

endm